apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: nodsapp
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlluVnVkSGswTWpBd09rcGhlWEpoYWtBME1qQXciCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
